### PR TITLE
Port dmx to TypeScript

### PR DESCRIPTION
**Pull request by Granjow**
This PR refers to #99.

Please comment on the first draft. Warning: It does not run yet as the port is WIP.

### CODE REVIEW

**Comment by hrueger** [comment]
Hi @Granjow ,
Can I help with this PR?

I'd really like to see this getting merged, as I want to add DMX receiving functionality. This will be way easier using TypeScript.

**Comment by Granjow** [comment]
Hi @hrueger , yes, that would be kind. Most important would be a short review of the current TypeScript interface (to see if it makes sense and if it would work for you too) before we start porting the code. If it looks okay from your side, I would then complete the Enttec driver and I'd be very happy about any help in the other drivers and in general!

**Comment by hrueger** [comment]
@Granjow I've sent an email about collaborating to the mail address on your website.

**Comment by Cyberuben** [comment]
Is there still any activity on this? I'd love to see this working

**Comment by Granjow** [comment]
From our side the port should be complete! Some drivers are even tested.

Also, Enttec USB Open works now.

Open for review/merge!

**Comment by hrueger** [comment]
@wiedi Any update on this?
I'm using it currently and it works great.

**Comment by wiedi** [comment]
Hi, when this was proposed I thought this was just about adding some type annotations, while the rest would stay compatible.
Now this seems to be a 10k+ line rewrite into a language I don't understand.

I am not able to review this or maintain it.

I understand that a lot of energy went into this and that it seems to be useful. Given that this breaks the API maybe it would make sense to move this into a separate repository? I'd be happy to create a "dmx-ts" or similar thing under the node-dmx organisation and give you admin rights. Would that make sense?

**Comment by hrueger** [comment]
I can totally understand you. I'd be happy with `dmx-ts`!

**Comment by wiedi** [comment]
Alrighty. I've sent an invite to you @hrueger and @Granjow that should grant admin access to it. With that you should be able to push and then switch the repo public. Let me know if you need anything more.

**Comment by hrueger** [comment]
Thanks a lot. I'll push tomorrow.

**Comment by hrueger** [comment]
@wiedi I'm done. Sorry for the commit history, but I've had a few problems with the spec test which would work on windows but not on linux. Hope it doesn't matter 👍

@Granjow I added / changed a couple of things:
- spec test now works on Linux
- setup auto-publishing to npm on git tags (instructions are at the bottom of the readme)
- fixed the repository urls in the `package.json` file
- only pack `dist` folder and not `src` into the package
- run the CI on GitHub Actions instead of Travis CI

**Comment by wiedi** [comment]
Fantastic!

**Comment by Granjow** [comment]
@wiedi Thanks, could you send the invitation again? Was offline the last few days.

@hrueger Sounds very good, thank you!

Once I have access I can restore the commit history, I'm a bit used to doing such stuff ;)

**Comment by wiedi** [comment]
Sure, done

**Pull request closed without merging**
