### PR TITLE
upgrade serial port to 7.x

### PR DESCRIPTION
**Pull request by sdeboeck**

### CODE REVIEW

**Comment by sdeboeck** [comment]
Still have to be tested with a usb driver. 
Compiles on node v10 and v12

**Comment by Fensterbank** [comment]
@sdeboeck Thanks for your PR.
I noticed you removed `package-lock.json` from the repository.
This file is ment to be committed to the repository.
If you re-add the previously existing `package-lock.json` and run an `npm install`, the file should be updated containing the new serial port version.

I will make a short test with my usb driver ASAP.

**Comment by sdeboeck** [comment]
@Fensterbank the package-lock.json is still in the repository. 
The diff isn't showing because to much changes.

I also will try to test it with a usb driver in the beginning of next week.

**Comment by foxxyz** [comment]
FYI: I ran a basic test with an Enttec USB DMX Pro using @sdeboeck's fork and did not notice any change in functionality.

**Comment by Fensterbank** [comment]
Thanks. Tested it too and seems good.

**Comment by H-s-O** [comment]
Has this been published yet? `npm i dmx` still tries to install `serialport@6.2.2` which crashes on build with Node 12.

**Comment by bluemaex** [comment]
@H-s-O Thanks for the reminder. Just published a new version.

**Comment by H-s-O** [comment]
@bluemaex Thanks!

**Pull request merged**
