### PR TITLE
added socketio driver

### PR DESCRIPTION
**Pull request by hrueger**
This driver uses socketio to send the universe data as an array over to other programms.
The debug mode prints connect and disconnect messages.

### CODE REVIEW

**Comment by hrueger** [comment]
Is there anything else which has to be done before this PR can be merged?

**Comment by Fensterbank** [comment]
While I did not make tests, it looks fine for me. Thanks for your work.
@wiedi or @bluemaex, any thoughts on this? I think we can merge it, since it does not affect any existing things and obviously works for @hrueger.

**Comment by wiedi** [comment]
Maybe it should be called "socketio" instead of just "socket" because that's very generic. Other than that I think it's fine

**Comment by hrueger** [comment]
In the commit message there's a spelling misstake, but in the code it is written correctly

**Comment by wiedi** [comment]
Thanks! I've squashed it so the commit message is fine.

**Comment by hrueger** [comment]
Oh, I somehow forgot to add the driver to the readme's driver list, should I create a new pull request for this? Or do you think that this is not necessary since it is not a 'real' hardware driver?

**Comment by wiedi** [comment]
Sure, correct documentation would be good :)

**Pull request merged**
